[package]
name = "tee_host"
version = "0.1.0"
edition = "2018"

[workspace]

[dependencies]
wasmer-runtime = "0.14.1"
wasmer-middleware-common = "0.14.1"
wasmer-runtime-core = "0.14.1"
wasmer-singlepass-backend = "0.14.1"